create table if not exists public.web_requests (
 id bigint generated by default as identity primary key,
 code text unique not null,
 created_at timestamptz not null default now(),
 status text not null default 'Pendiente de pago',
 customer jsonb not null default '{}'::jsonb,
 items jsonb not null default '[]'::jsonb,
 quantity integer not null default 0,
 estimated_total numeric not null default 0,
 estimated_from date,
 estimated_to date,
 notes text
);
alter table public.web_requests enable row level security;
drop policy if exists "web_requests_public_insert" on public.web_requests;
create policy "web_requests_public_insert" on public.web_requests for insert to anon, authenticated with check (status='Pendiente de pago');
drop policy if exists "web_requests_admin_read" on public.web_requests;
create policy "web_requests_admin_read" on public.web_requests for select to authenticated using (true);
drop policy if exists "web_requests_admin_update" on public.web_requests;
create policy "web_requests_admin_update" on public.web_requests for update to authenticated using (true) with check (true);
