-- Tu Vida En Tinta - Estadísticas del catálogo
-- Ejecutar una sola vez en Supabase > SQL Editor > New query > Run.

create table if not exists public.catalog_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('catalog_visit','product_view','cart_add','cart_remove','order_sent','order_product','feedback')),
  visitor_id text not null,
  session_id text not null,
  product_id text,
  product_name text,
  category text,
  quantity integer not null default 0,
  locality text,
  province text,
  postal_code text,
  rating text check (rating is null or rating in ('positive','negative')),
  comment text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists catalog_events_created_at_idx on public.catalog_events (created_at desc);
create index if not exists catalog_events_event_type_idx on public.catalog_events (event_type);
create index if not exists catalog_events_product_id_idx on public.catalog_events (product_id);
create index if not exists catalog_events_visitor_id_idx on public.catalog_events (visitor_id);

alter table public.catalog_events enable row level security;

drop policy if exists "catalog_events_public_insert" on public.catalog_events;
create policy "catalog_events_public_insert"
on public.catalog_events for insert
to anon, authenticated
with check (
  length(visitor_id) between 8 and 120
  and length(session_id) between 8 and 120
  and event_type in ('catalog_visit','product_view','cart_add','cart_remove','order_sent','order_product','feedback')
);

drop policy if exists "catalog_events_admin_read" on public.catalog_events;
create policy "catalog_events_admin_read"
on public.catalog_events for select
to authenticated
using (true);

-- No se habilita UPDATE ni DELETE para visitantes públicos.
