import React,{useMemo,useState} from 'react'
import {Title,Field,Badge} from '../components/UI'
import {money} from '../lib/format'
import {importClientsFromOrders,upsertClient} from '../lib/clients'
import {customerProfile} from '../lib/operations'

export default function Clients({db,onSave,go}){
 const [q,setQ]=useState(''),blank={firstName:'',lastName:'',name:'',phone:'',dni:'',address:'',locality:'',district:'',province:'',postalCode:'',notes:''},[form,setForm]=useState(blank),[openId,setOpenId]=useState(null),clients=db.clients||[]
 async function add(e){e.preventDefault();if(!form.firstName.trim())return alert('Ingresá el nombre del cliente.');if(!form.lastName.trim())return alert('Ingresá el apellido del cliente.');const fullName=[form.firstName,form.lastName].filter(Boolean).join(' ').trim(),next=upsertClient(clients,{...form,name:fullName});await onSave({...db,clients:next});setForm(blank);alert(next.length>clients.length?'Cliente guardado.':'Cliente actualizado sin duplicarlo.')}
 async function importHistory(){if(!db.orders?.length)return alert('Todavía no hay pedidos para importar.');const next=importClientsFromOrders(clients,db.orders);await onSave({...db,clients:next});alert(`Importación terminada. Ahora hay ${next.length} clientes registrados.`)}
 async function remove(id){if(confirm('¿Eliminar este cliente?'))await onSave({...db,clients:clients.filter(c=>c.id!==id)})}
 const list=clients.filter(c=>`${c.name} ${c.phone} ${c.dni||''} ${c.address||''} ${c.locality||c.zone||''} ${c.district||''} ${c.province||''} ${c.postalCode||''}`.toLowerCase().includes(q.toLowerCase()))
 function clientOrders(c){return customerProfile(db,c).orders.slice().reverse()}
 function openWA(c){const n=String(c.phone||'').replace(/\D/g,'');window.open(`https://wa.me/${n}?text=${encodeURIComponent('Hola '+c.name+', te escribimos de Tu Vida En Tinta.')}`,'_blank')}
 function newOrder(c){const draft={firstName:c.firstName||String(c.name||'').split(/\s+/)[0]||'',lastName:c.lastName||String(c.name||'').split(/\s+/).slice(1).join(' '),client:c.name||'',phone:c.phone||'',dni:c.dni||'',email:c.email||'',address:c.address||'',betweenStreets:c.betweenStreets||'',locality:c.locality||'',district:c.district||'',province:c.province||'',postalCode:c.postalCode||''};try{localStorage.setItem('polifan-order-draft-v1',JSON.stringify(draft))}catch{};go?.('new')}
 const stats=useMemo(()=>({withOrders:clients.filter(c=>customerProfile(db,c).orders.length).length,total:(db.orders||[]).filter(o=>o.status!=='Cancelado').reduce((a,o)=>a+Number(o.total||0),0),frequent:clients.filter(c=>customerProfile(db,c).type==='Frecuente').length}),[clients,db.orders])
 function favorites(orders){const totals={};orders.forEach(o=>(o.items||[]).forEach(i=>{if(i.figure&&i.inventoryTracked!==false)totals[i.figure]=(totals[i.figure]||0)+Number(i.qty||0)}));return Object.entries(totals).sort((a,b)=>b[1]-a[1]).slice(0,3)}
 return <><Title title="Historial de clientes" sub="Ficha completa, origen, frecuencia, compras y acceso directo a un nuevo pedido." actions={<button className="primary" onClick={importHistory}>Importar clientes desde pedidos</button>}/>
 <div className="cards client-summary"><div className="kpi"><small>Clientes guardados</small><b>{clients.length}</b></div><div className="kpi"><small>Con pedidos</small><b>{stats.withOrders}</b></div><div className="kpi"><small>Frecuentes</small><b>{stats.frequent}</b></div><div className="kpi"><small>Ventas históricas</small><b>{money(stats.total)}</b></div></div>
 <form className="panel" onSubmit={add}><div className="form-grid"><Field label="Nombre"><input value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value,name:[e.target.value,form.lastName].filter(Boolean).join(' ')})}/></Field><Field label="Apellido"><input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value,name:[form.firstName,e.target.value].filter(Boolean).join(' ')})}/></Field><Field label="Teléfono"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="DNI (opcional)"><input inputMode="numeric" value={form.dni} onChange={e=>setForm({...form,dni:e.target.value.replace(/\D/g,'')})}/></Field><Field label="Dirección"><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="Localidad"><input value={form.locality} onChange={e=>setForm({...form,locality:e.target.value})}/></Field><Field label="Partido / Departamento"><input value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/></Field><Field label="Provincia"><input value={form.province} onChange={e=>setForm({...form,province:e.target.value})}/></Field><Field label="Código postal"><input value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/></Field><Field label="Observaciones"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><button className="primary">Guardar o actualizar cliente</button></form>
 <div className="panel filters"><input placeholder="Buscar por nombre, teléfono, DNI, localidad o CP…" value={q} onChange={e=>setQ(e.target.value)}/></div>
 <div className="client-list">{list.map(c=>{const profile=customerProfile(db,c),orders=clientOrders(c),spent=profile.spent,pieces=orders.flatMap(o=>o.items||[]).filter(i=>i.inventoryTracked!==false).reduce((a,i)=>a+Number(i.qty||0),0),fav=favorites(orders),isOpen=openId===c.id;return <div className="panel client-card" key={c.id}><div className="client-card-head"><div><div className="client-name-row"><h3>{c.name}</h3><span className={'vip-badge client-type-'+profile.type.toLowerCase()}>{profile.type==='Frecuente'?'★ ':''}{profile.type.toUpperCase()}</span></div><p>{c.phone||'Sin teléfono'}{c.dni?` · DNI ${c.dni}`:''}</p><small>{c.address||'Sin dirección'} · {[c.locality||c.zone,c.district,c.province].filter(Boolean).join(', ')} · CP {c.postalCode||'-'}</small><small>Origen principal: <b>{profile.source}</b>{profile.last?` · Última compra: ${profile.last.date||profile.last.createdAt?.slice(0,10)||'-'}`:''}</small>{c.notes&&<small>{c.notes}</small>}</div><div className="client-metrics"><span><b>{orders.length}</b><small>pedidos</small></span><span><b>{pieces}</b><small>piezas</small></span><span><b>{money(spent)}</b><small>gastado</small></span></div><div className="row-actions"><button className="primary" onClick={()=>newOrder(c)}>＋ Nuevo pedido</button>{c.phone&&<button className="whatsapp" onClick={()=>openWA(c)}>WhatsApp</button>}<button className="ghost" onClick={()=>setOpenId(isOpen?null:c.id)}>{isOpen?'Ocultar':'Ver historial'}</button><button className="danger" onClick={()=>remove(c.id)}>Eliminar</button></div></div>{isOpen&&<div className="client-history"><div className="favorite-box"><b>Figuras favoritas</b>{fav.length?<div>{fav.map(([name,qty])=><span key={name}>{name}: {qty}</span>)}</div>:<small>Sin datos todavía.</small>}</div><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Fecha</th><th>Entrega</th><th>Piezas</th><th>Estado</th><th>Origen</th><th>Total</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>#{o.number}</td><td>{o.date||'-'}</td><td>{o.delivery||'-'}</td><td>{(o.items||[]).filter(i=>i.inventoryTracked!==false).reduce((a,i)=>a+Number(i.qty||0),0)}</td><td><Badge status={o.status}/></td><td>{o.customerSource||o.source||'-'}</td><td>{money(o.total)}</td></tr>)}{!orders.length&&<tr><td colSpan="7">Todavía no tiene pedidos.</td></tr>}</tbody></table></div></div>}</div>})}{!list.length&&<div className="panel">No hay clientes cargados.</div>}</div></>
}
