import React,{useMemo,useState} from 'react'
import {Title,Field} from '../components/UI'
import {money} from '../lib/format'

const defaults={sheetCost:8233,figuresPerSheet:10,laborPerFigure:300,glueContainerCost:9800,glueYieldFigures:200,cutMinutesPerFigure:5,glueMinutesPerFigure:3,packMinutesPerOrder:12,boxes:{'30x20x20':2279.50,'40x30x30':3037.40,'50x40x30':3853.89,'50x40x40':4134.95,'60x40x40':4803.72}}
const boxNames={'30x20x20':'Caja 30×20×20','40x30x30':'Caja 40×30×30','50x40x30':'Caja 50×40×30','50x40x40':'Caja 50×40×40','60x40x40':'Caja 60×40×40'}
export default function CostSettings({db,onSave}){
 const [form,setForm]=useState(()=>({...defaults,...(db.costSettings||{}),boxes:{...defaults.boxes,...(db.costSettings?.boxes||{})}}))
 const unit=useMemo(()=>Number(form.sheetCost||0)/Math.max(1,Number(form.figuresPerSheet||1))+Number(form.laborPerFigure||0)+Number(form.glueContainerCost||0)/Math.max(1,Number(form.glueYieldFigures||1)),[form])
 const set=(k,v)=>setForm(f=>({...f,[k]:v}))
 const save=async()=>{const normalized={...form,sheetCost:Number(form.sheetCost||0),figuresPerSheet:Number(form.figuresPerSheet||10),laborPerFigure:Number(form.laborPerFigure||0),glueContainerCost:Number(form.glueContainerCost||0),glueYieldFigures:Number(form.glueYieldFigures||1),cutMinutesPerFigure:Number(form.cutMinutesPerFigure||0),glueMinutesPerFigure:Number(form.glueMinutesPerFigure||0),packMinutesPerOrder:Number(form.packMinutesPerOrder||0),boxes:Object.fromEntries(Object.entries(form.boxes||{}).map(([k,v])=>[k,Number(v||0)]))};await onSave({...db,costSettings:normalized});alert('Costos actualizados. Los nuevos cálculos usarán estos valores.')}
 return <><Title title="Costos de producción" sub="Actualizá materia prima, mano de obra, pegamento, embalajes y tiempos sin tocar el código."/>
 <div className="cards"><div className="kpi"><small>Costo estimado por figura</small><b>{money(unit)}</b></div><div className="kpi"><small>Material por figura</small><b>{money(Number(form.sheetCost||0)/Math.max(1,Number(form.figuresPerSheet||1)))}</b></div><div className="kpi"><small>Pegamento por figura</small><b>{money(Number(form.glueContainerCost||0)/Math.max(1,Number(form.glueYieldFigures||1)))}</b></div></div>
 <section className="panel"><h3>Producción</h3><div className="form-grid"><Field label="Costo de placa"><input type="number" value={form.sheetCost} onChange={e=>set('sheetCost',e.target.value)}/></Field><Field label="Figuras por placa"><input type="number" value={form.figuresPerSheet} onChange={e=>set('figuresPerSheet',e.target.value)}/></Field><Field label="Pegado por figura"><input type="number" value={form.laborPerFigure} onChange={e=>set('laborPerFigure',e.target.value)}/></Field><Field label="Costo envase de pegamento"><input type="number" value={form.glueContainerCost} onChange={e=>set('glueContainerCost',e.target.value)}/></Field><Field label="Rendimiento del pegamento (figuras)"><input type="number" value={form.glueYieldFigures} onChange={e=>set('glueYieldFigures',e.target.value)}/></Field></div></section>
 <section className="panel"><h3>Tiempos para estimar carga de trabajo</h3><div className="form-grid"><Field label="Minutos de corte por figura"><input type="number" step="0.5" value={form.cutMinutesPerFigure} onChange={e=>set('cutMinutesPerFigure',e.target.value)}/></Field><Field label="Minutos de pegado por figura"><input type="number" step="0.5" value={form.glueMinutesPerFigure} onChange={e=>set('glueMinutesPerFigure',e.target.value)}/></Field><Field label="Minutos de embalaje por pedido"><input type="number" step="1" value={form.packMinutesPerOrder} onChange={e=>set('packMinutesPerOrder',e.target.value)}/></Field></div></section>
 <section className="panel"><h3>Costo total de cada embalaje</h3><div className="form-grid">{Object.entries(form.boxes).map(([k,v])=><Field key={k} label={boxNames[k]||k}><input type="number" step="0.01" value={v} onChange={e=>setForm(f=>({...f,boxes:{...f.boxes,[k]:e.target.value}}))}/></Field>)}</div><small>Estos valores incluyen caja + burbuja + cintas + film.</small></section>
 <div className="actions"><button className="primary" onClick={save}>Guardar costos</button></div></>
}
