import React,{useMemo,useState} from 'react'
import {Title,Field} from '../components/UI'
import {money} from '../lib/format'
const boxNames={'30x20x20':'Caja 30×20×20','40x30x30':'Caja 40×30×30','50x40x30':'Caja 50×40×30','50x40x40':'Caja 50×40×40','60x40x40':'Caja 60×40×40'}
const boxPurchase={'30x20x20':1500,'40x30x30':1700,'50x40x30':2100,'50x40x40':2100,'60x40x40':2500}
const usageDefaults={'30x20x20':{bubbleM2:.582,packingTapeM:3.10,blackFilmM:2,fragileTapeM:1.8},'40x30x30':{bubbleM2:1.2,packingTapeM:4.2,blackFilmM:2.8,fragileTapeM:2.6},'50x40x30':{bubbleM2:1.709,packingTapeM:5.1,blackFilmM:3.2,fragileTapeM:3},'50x40x40':{bubbleM2:2.036,packingTapeM:5.3,blackFilmM:3.6,fragileTapeM:3.4},'60x40x40':{bubbleM2:2.327,packingTapeM:6.2,blackFilmM:4,fragileTapeM:3.6}}
const materialDefaults={bubble:{cost:16000,lengthM:25,widthMm:1000},packingTape:{cost:1090,lengthM:40,widthMm:48},blackFilm:{cost:19995,lengthM:160,widthMm:500},fragileTape:{cost:1616,lengthM:40,widthMm:48}}
const defaults={sheetCost:8233,figuresPerSheet:10,glueContainerCost:8200,glueYieldFigures:100,cutMinutesPerFigure:5,glueMinutesPerFigure:3,packMinutesPerOrder:12,packagingMaterials:materialDefaults,boxPurchaseCosts:boxPurchase,boxUsage:usageDefaults,boxes:{}}
const num=v=>Number(v||0)
function rates(m){const b=m.bubble||materialDefaults.bubble,p=m.packingTape||materialDefaults.packingTape,f=m.blackFilm||materialDefaults.blackFilm,g=m.fragileTape||materialDefaults.fragileTape;return{bubblePerM2:num(b.cost)/Math.max(.001,num(b.lengthM)*num(b.widthMm)/1000),packingPerM:num(p.cost)/Math.max(.001,num(p.lengthM)),filmPerM:num(f.cost)/Math.max(.001,num(f.lengthM)),fragilePerM:num(g.cost)/Math.max(.001,num(g.lengthM))}}
function boxCost(k,form){const u=form.boxUsage?.[k]||usageDefaults[k],r=rates(form.packagingMaterials||materialDefaults),box=num(form.boxPurchaseCosts?.[k]??boxPurchase[k]);const x={box,bubble:num(u.bubbleM2)*r.bubblePerM2,packingTape:num(u.packingTapeM)*r.packingPerM,blackFilm:num(u.blackFilmM)*r.filmPerM,fragileTape:num(u.fragileTapeM)*r.fragilePerM};return{...x,total:Object.values(x).reduce((a,b)=>a+b,0)}}
export default function CostSettings({db,onSave}){
 const [form,setForm]=useState(()=>{const s=db.costSettings||{};return{...defaults,...s,laborPerFigure:0,packagingMaterials:{...materialDefaults,...s.packagingMaterials},boxPurchaseCosts:{...boxPurchase,...s.boxPurchaseCosts},boxUsage:Object.fromEntries(Object.keys(boxNames).map(k=>[k,{...usageDefaults[k],...(s.boxUsage?.[k]||{})}]))}})
 const glueUnit=useMemo(()=>num(form.glueContainerCost)/Math.max(1,num(form.glueYieldFigures)),[form.glueContainerCost,form.glueYieldFigures])
 const unit=useMemo(()=>num(form.sheetCost)/Math.max(1,num(form.figuresPerSheet))+glueUnit,[form.sheetCost,form.figuresPerSheet,glueUnit])
 const costs=useMemo(()=>Object.fromEntries(Object.keys(boxNames).map(k=>[k,boxCost(k,form)])),[form])
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));const setMaterial=(k,x,v)=>setForm(f=>({...f,packagingMaterials:{...f.packagingMaterials,[k]:{...f.packagingMaterials[k],[x]:v}}}));const setUsage=(k,x,v)=>setForm(f=>({...f,boxUsage:{...f.boxUsage,[k]:{...f.boxUsage[k],[x]:v}}}))
 const save=async()=>{const boxes=Object.fromEntries(Object.entries(costs).map(([k,v])=>[k,v.total]));const normalized={...form,laborPerFigure:0,sheetCost:num(form.sheetCost),figuresPerSheet:num(form.figuresPerSheet)||10,glueContainerCost:num(form.glueContainerCost),glueYieldFigures:num(form.glueYieldFigures)||1,cutMinutesPerFigure:num(form.cutMinutesPerFigure),glueMinutesPerFigure:num(form.glueMinutesPerFigure),packMinutesPerOrder:num(form.packMinutesPerOrder),boxes};await onSave({...db,costSettings:normalized});alert('Costos actualizados. El pegamento por figura se calcula automáticamente por costo del envase ÷ rendimiento.')}
 return <><Title title="Costos de producción" sub="Editá precios, medidas, metros y consumos. La app calcula automáticamente el gasto real por caja."/>
 <div className="cards"><div className="kpi"><small>Costo estimado por figura</small><b>{money(unit)}</b></div><div className="kpi"><small>Pegamento por figura</small><b>{money(glueUnit)}</b></div><div className="kpi"><small>Caja 40×30×30 completa</small><b>{money(costs['40x30x30'].total)}</b></div></div>
 <section className="panel"><h3>Producción y pegamento</h3><div className="form-grid"><Field label="Costo de placa"><input type="number" value={form.sheetCost} onChange={e=>set('sheetCost',e.target.value)}/></Field><Field label="Figuras por placa"><input type="number" value={form.figuresPerSheet} onChange={e=>set('figuresPerSheet',e.target.value)}/></Field><Field label="Costo envase de pegamento"><input type="number" value={form.glueContainerCost} onChange={e=>set('glueContainerCost',e.target.value)}/></Field><Field label="Rendimiento del pegamento (piezas)"><input type="number" value={form.glueYieldFigures} onChange={e=>set('glueYieldFigures',e.target.value)}/></Field></div><small>El costo de pegamento por figura se calcula automáticamente: {money(num(form.glueContainerCost))} ÷ {Math.max(1,num(form.glueYieldFigures))} = <b>{money(glueUnit)}</b>.</small></section>
 <section className="panel"><h3>Rollos y materiales de embalaje</h3><small>Cargá lo que pagás y la medida real del rollo.</small><div className="table-wrap"><table><thead><tr><th>Material</th><th>Costo</th><th>Largo rollo (m)</th><th>Ancho (mm)</th><th>Costo unitario</th></tr></thead><tbody>{[['bubble','Burbuja'],['packingTape','Cinta de embalar'],['blackFilm','Film negro'],['fragileTape','Cinta frágil']].map(([k,label])=>{const m=form.packagingMaterials[k],r=rates(form.packagingMaterials),rate=k==='bubble'?r.bubblePerM2:k==='packingTape'?r.packingPerM:k==='blackFilm'?r.filmPerM:r.fragilePerM;return <tr key={k}><td><b>{label}</b></td><td><input type="number" value={m.cost} onChange={e=>setMaterial(k,'cost',e.target.value)}/></td><td><input type="number" step="0.1" value={m.lengthM} onChange={e=>setMaterial(k,'lengthM',e.target.value)}/></td><td><input type="number" value={m.widthMm} onChange={e=>setMaterial(k,'widthMm',e.target.value)}/></td><td><b>{money(rate)} / {k==='bubble'?'m²':'m'}</b></td></tr>})}</tbody></table></div></section>
 <section className="panel"><h3>Consumo y costo real por caja</h3><div className="table-wrap"><table><thead><tr><th>Caja</th><th>Costo caja</th><th>Burbuja m²</th><th>Cinta embalar m</th><th>Film negro m</th><th>Cinta frágil m</th><th>Total</th></tr></thead><tbody>{Object.keys(boxNames).map(k=>{const u=form.boxUsage[k],c=costs[k];return <tr key={k}><td><b>{boxNames[k]}</b></td><td><input type="number" value={form.boxPurchaseCosts[k]} onChange={e=>setForm(f=>({...f,boxPurchaseCosts:{...f.boxPurchaseCosts,[k]:e.target.value}}))}/></td><td><input type="number" step="0.01" value={u.bubbleM2} onChange={e=>setUsage(k,'bubbleM2',e.target.value)}/></td><td><input type="number" step="0.01" value={u.packingTapeM} onChange={e=>setUsage(k,'packingTapeM',e.target.value)}/></td><td><input type="number" step="0.01" value={u.blackFilmM} onChange={e=>setUsage(k,'blackFilmM',e.target.value)}/></td><td><input type="number" step="0.01" value={u.fragileTapeM} onChange={e=>setUsage(k,'fragileTapeM',e.target.value)}/></td><td><b>{money(c.total)}</b></td></tr>})}</tbody></table></div></section>
 <section className="panel"><h3>Tiempos para estimar carga de trabajo</h3><div className="form-grid"><Field label="Minutos de corte por figura"><input type="number" step="0.5" value={form.cutMinutesPerFigure} onChange={e=>set('cutMinutesPerFigure',e.target.value)}/></Field><Field label="Minutos de pegado por figura"><input type="number" step="0.5" value={form.glueMinutesPerFigure} onChange={e=>set('glueMinutesPerFigure',e.target.value)}/></Field><Field label="Minutos de embalaje por pedido"><input type="number" step="1" value={form.packMinutesPerOrder} onChange={e=>set('packMinutesPerOrder',e.target.value)}/></Field></div></section><div className="actions"><button className="primary" onClick={save}>Guardar costos y recalcular cajas</button></div></>
}
