import React,{useState} from 'react'
import {Title} from '../components/UI'
import {fileToOptimizedDataUrl} from '../lib/imageOptimize'
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)
export default function CustomerTrust({db,onSave}){
 const [review,setReview]=useState({name:'',text:'',image:''});const [photo,setPhoto]=useState({name:'',caption:'',image:''});const [optimizing,setOptimizing]=useState(false)
 const reviews=db.customerReviews||[],photos=db.customerPhotos||[]
 const chooseImage=async(file,setter)=>{if(!file)return;setOptimizing(true);try{const image=await fileToOptimizedDataUrl(file,{maxWidth:1400,maxHeight:1400,quality:.82});setter(v=>({...v,image}))}catch{alert('No se pudo procesar la imagen.')}finally{setOptimizing(false)}}
 const saveReview=async()=>{if(!review.text.trim())return alert('Escribí la reseña.');await onSave({...db,customerReviews:[...reviews,{id:uid(),...review,active:true,featured:false,createdAt:new Date().toISOString()}]});setReview({name:'',text:'',image:''})}
 const savePhoto=async()=>{if(!photo.image)return alert('Elegí una foto.');await onSave({...db,customerPhotos:[...photos,{id:uid(),...photo,active:true,featured:false,createdAt:new Date().toISOString()}]});setPhoto({name:'',caption:'',image:''})}
 const del=async(type,id)=>{if(!confirm('¿Eliminar?'))return;await onSave({...db,[type]:(db[type]||[]).filter(x=>x.id!==id)})}
 const toggleFeatured=async(type,id)=>{const list=(db[type]||[]).map(x=>x.id===id?{...x,featured:!x.featured}:x);await onSave({...db,[type]:list})}
 const sortFeatured=list=>list.slice().sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured))||String(b.createdAt||'').localeCompare(String(a.createdAt||'')))
 return <><Title title="Confianza de clientes" sub="Fotos y reseñas optimizadas automáticamente. Marcá las mejores como destacadas para mostrarlas primero."/>
 {optimizing&&<div className="notice"><b>Optimizando imagen…</b><span>Reducimos el peso para que el catálogo cargue más rápido.</span></div>}
 <div className="analytics-grid"><section className="panel"><h3>📸 Fotos de clientes</h3><input placeholder="Nombre (opcional)" value={photo.name} onChange={e=>setPhoto({...photo,name:e.target.value})}/><input placeholder="Texto de la foto" value={photo.caption} onChange={e=>setPhoto({...photo,caption:e.target.value})}/><input type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0],setPhoto)}/>{photo.image&&<div className="trust-upload-preview"><img src={photo.image} alt="Vista previa"/></div>}<button className="primary" type="button" disabled={optimizing} onClick={savePhoto}>Agregar foto</button>{sortFeatured(photos).map(x=><div className="trust-admin-item" key={x.id}>{x.image&&<img src={x.image} alt="Cliente"/>}<span><b>{x.featured?'⭐ ':''}{x.name||'Cliente'}</b><small>{x.caption}</small></span><button className="ghost smallbtn" onClick={()=>toggleFeatured('customerPhotos',x.id)}>{x.featured?'Quitar destacado':'Destacar'}</button><button className="danger smallbtn" onClick={()=>del('customerPhotos',x.id)}>Eliminar</button></div>)}</section>
 <section className="panel"><h3>⭐ Reseñas</h3><input placeholder="Nombre del cliente" value={review.name} onChange={e=>setReview({...review,name:e.target.value})}/><textarea placeholder="Reseña recibida..." value={review.text} onChange={e=>setReview({...review,text:e.target.value})}/><label className="trust-review-upload"><b>Imagen de la reseña (opcional)</b><input type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0],setReview)}/></label>{review.image&&<div className="trust-upload-preview"><img src={review.image} alt="Vista previa de reseña"/></div>}<button className="primary" type="button" disabled={optimizing} onClick={saveReview}>Agregar reseña</button>{sortFeatured(reviews).map(x=><div className="trust-admin-item" key={x.id}>{x.image&&<img src={x.image} alt="Imagen de reseña"/>}<span><b>{x.featured?'⭐ ':''}★★★★★ {x.name||'Cliente'}</b><small>{x.text}</small></span><button className="ghost smallbtn" onClick={()=>toggleFeatured('customerReviews',x.id)}>{x.featured?'Quitar destacado':'Destacar'}</button><button className="danger smallbtn" onClick={()=>del('customerReviews',x.id)}>Eliminar</button></div>)}</section></div></>
}
