import React,{useEffect,useState} from 'react'
import {Title} from '../components/UI'
import {fileToOptimizedDataUrl} from '../lib/imageOptimize'
import {supabase} from '../supabase'
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)
export default function CustomerTrust({db,onSave}){
 const [review,setReview]=useState({name:'',text:'',image:''});const [photo,setPhoto]=useState({name:'',caption:'',image:''});const [optimizing,setOptimizing]=useState(false)
 const [catalogReviews,setCatalogReviews]=useState([]);const [loadingCatalog,setLoadingCatalog]=useState(true)
 const reviews=db.customerReviews||[],photos=db.customerPhotos||[]
 const chooseImage=async(file,setter)=>{if(!file)return;setOptimizing(true);try{const image=await fileToOptimizedDataUrl(file,{maxWidth:1400,maxHeight:1400,quality:.82});setter(v=>({...v,image}))}catch{alert('No se pudo procesar la imagen.')}finally{setOptimizing(false)}}
 const saveReview=async()=>{if(!review.text.trim()&&!review.image)return alert('Escribí una reseña o subí una imagen.');await onSave({...db,customerReviews:[...reviews,{id:uid(),...review,active:true,featured:false,createdAt:new Date().toISOString()}]});setReview({name:'',text:'',image:''})}
 const savePhoto=async()=>{if(!photo.image)return alert('Elegí una foto.');await onSave({...db,customerPhotos:[...photos,{id:uid(),...photo,active:true,featured:false,createdAt:new Date().toISOString()}]});setPhoto({name:'',caption:'',image:''})}
 const del=async(type,id)=>{if(!confirm('¿Eliminar?'))return;await onSave({...db,[type]:(db[type]||[]).filter(x=>x.id!==id)})}
 const toggleFeatured=async(type,id)=>{const list=(db[type]||[]).map(x=>x.id===id?{...x,featured:!x.featured}:x);await onSave({...db,[type]:list})}
 const sortFeatured=list=>list.slice().sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured))||String(b.createdAt||'').localeCompare(String(a.createdAt||'')))
 async function loadCatalogReviews(){setLoadingCatalog(true);const {data,error}=await supabase.from('catalog_reviews').select('id,name,rating,comment,photo_url,order_number,status,created_at,approved_at').order('created_at',{ascending:false});if(error)console.error(error);setCatalogReviews(data||[]);setLoadingCatalog(false)}
 useEffect(()=>{loadCatalogReviews()},[])
 async function moderate(id,status){const patch={status,updated_at:new Date().toISOString(),approved_at:status==='approved'?new Date().toISOString():null};const {error}=await supabase.from('catalog_reviews').update(patch).eq('id',id);if(error)return alert('No se pudo actualizar la opinión: '+error.message);await loadCatalogReviews()}
 async function removeCatalogReview(id){if(!confirm('¿Eliminar definitivamente esta opinión?'))return;const {error}=await supabase.from('catalog_reviews').delete().eq('id',id);if(error)return alert('No se pudo eliminar: '+error.message);await loadCatalogReviews()}
 const pending=catalogReviews.filter(x=>x.status==='pending'),published=catalogReviews.filter(x=>x.status==='approved'),rejected=catalogReviews.filter(x=>x.status==='rejected')
 return <><Title title="Confianza de clientes" sub="Moderá las opiniones que llegan desde el catálogo y administrá las fotos/reseñas cargadas manualmente."/>
 {optimizing&&<div className="notice"><b>Optimizando imagen…</b><span>Reducimos el peso para que el catálogo cargue más rápido.</span></div>}
 <section className="panel" style={{marginBottom:16}}><div className="panel-heading"><div><h3>💬 Opiniones recibidas desde el catálogo</h3><small>Las nuevas quedan pendientes hasta que las apruebes. Las aprobadas aparecen automáticamente en el catálogo público.</small></div><button className="ghost" onClick={loadCatalogReviews}>Actualizar</button></div>
 <div className="cards" style={{marginTop:12}}><div className="kpi"><small>Pendientes</small><b>{pending.length}</b></div><div className="kpi"><small>Publicadas</small><b>{published.length}</b></div><div className="kpi"><small>Rechazadas</small><b>{rejected.length}</b></div></div>
 {loadingCatalog?<p>Cargando opiniones…</p>:<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Pedido</th><th>Estrellas</th><th>Comentario</th><th>Foto</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{catalogReviews.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleDateString('es-AR')}</td><td><b>{x.name||'Cliente'}</b></td><td>{x.order_number?`#${x.order_number}`:'-'}</td><td>{'★'.repeat(Number(x.rating||0))}{'☆'.repeat(Math.max(0,5-Number(x.rating||0)))}</td><td style={{minWidth:220,maxWidth:420}}>{x.comment}</td><td>{x.photo_url?<a href={x.photo_url} target="_blank" rel="noreferrer">Ver foto</a>:'-'}</td><td><b>{x.status==='pending'?'Pendiente':x.status==='approved'?'Publicada':'Rechazada'}</b></td><td className="row-actions">{x.status!=='approved'&&<button className="primary" onClick={()=>moderate(x.id,'approved')}>Aprobar</button>}{x.status!=='rejected'&&<button className="ghost" onClick={()=>moderate(x.id,'rejected')}>Rechazar</button>}{x.status!=='pending'&&<button className="ghost" onClick={()=>moderate(x.id,'pending')}>Pendiente</button>}<button className="danger" onClick={()=>removeCatalogReview(x.id)}>Eliminar</button></td></tr>)}{!catalogReviews.length&&<tr><td colSpan="8">Todavía no llegaron opiniones desde el catálogo.</td></tr>}</tbody></table></div>}</section>
 <div className="analytics-grid"><section className="panel"><h3>📸 Fotos de clientes</h3><input placeholder="Nombre (opcional)" value={photo.name} onChange={e=>setPhoto({...photo,name:e.target.value})}/><input placeholder="Texto de la foto (opcional)" value={photo.caption} onChange={e=>setPhoto({...photo,caption:e.target.value})}/><input type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0],setPhoto)}/>{photo.image&&<div className="trust-upload-preview"><img src={photo.image} alt="Vista previa"/></div>}<button className="primary" type="button" disabled={optimizing} onClick={savePhoto}>Agregar foto</button>{sortFeatured(photos).map(x=><div className="trust-admin-item" key={x.id}>{x.image&&<img src={x.image} alt="Cliente"/>}<span><b>{x.featured?'⭐ ':''}{x.name||'Cliente'}</b>{x.caption&&<small>{x.caption}</small>}</span><button className="ghost smallbtn" onClick={()=>toggleFeatured('customerPhotos',x.id)}>{x.featured?'Quitar destacado':'Destacar'}</button><button className="danger smallbtn" onClick={()=>del('customerPhotos',x.id)}>Eliminar</button></div>)}</section>
 <section className="panel"><h3>⭐ Reseñas manuales</h3><input placeholder="Nombre del cliente (opcional)" value={review.name} onChange={e=>setReview({...review,name:e.target.value})}/><textarea placeholder="Reseña recibida (opcional si subís una imagen)..." value={review.text} onChange={e=>setReview({...review,text:e.target.value})}/><label className="trust-review-upload"><b>Imagen de la reseña (opcional)</b><input type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0],setReview)}/></label>{review.image&&<div className="trust-upload-preview"><img src={review.image} alt="Vista previa de reseña"/></div>}<button className="primary" type="button" disabled={optimizing} onClick={saveReview}>Agregar reseña</button>{sortFeatured(reviews).map(x=><div className="trust-admin-item" key={x.id}>{x.image&&<img src={x.image} alt="Imagen de reseña"/>}<span><b>{x.featured?'⭐ ':''}★★★★★ {x.name||'Cliente'}</b>{x.text&&<small>{x.text}</small>}</span><button className="ghost smallbtn" onClick={()=>toggleFeatured('customerReviews',x.id)}>{x.featured?'Quitar destacado':'Destacar'}</button><button className="danger smallbtn" onClick={()=>del('customerReviews',x.id)}>Eliminar</button></div>)}</section></div></>
}
