import React,{useMemo,useState} from 'react'
import {Title,Badge} from '../components/UI'
import {money} from '../lib/format'
import {orderPieces,todayArgentinaISO,DAILY_PIECE_LIMIT,sheetsForPieces} from '../lib/production'
import {stockRows,isOrderCommitted} from '../lib/inventory'
import {packagingNeeds,productionColumns} from '../lib/operations'
import '../refresh-v25.css'

export default function DashboardRefresh({db,go}){
  const [query,setQuery]=useState('')
  const today=todayArgentinaISO(),orders=db.orders||[]
  const active=orders.filter(o=>isOrderCommitted(o,today)),todayOrders=orders.filter(o=>o.delivery===today&&o.status!=='Cancelado')
  const todayPieces=todayOrders.reduce((s,o)=>s+orderPieces(o),0),pendingPieces=active.reduce((s,o)=>s+orderPieces(o),0)
  const overdue=orders.filter(o=>o.delivery&&o.delivery<today&&!['Cancelado','Entregado'].includes(o.status))
  const lowStock=stockRows(db).filter(r=>r.total<=r.min)
  const month=today.slice(0,7),monthOrders=orders.filter(o=>String(o.date||o.createdAt||'').slice(0,7)===month&&o.status!=='Cancelado')
  const revenue=monthOrders.reduce((s,o)=>s+Number(o.total||0),0),free=Math.max(0,DAILY_PIECE_LIMIT-todayPieces)
  const next=orders.filter(o=>o.delivery&&o.delivery>=today&&o.status!=='Cancelado').sort((a,b)=>String(a.delivery).localeCompare(String(b.delivery))).slice(0,5)
  const boxes=packagingNeeds(db,{from:today,days:7}),packagingStock=db.packagingStock||{}
  const boxesToBuy=boxes.map(row=>({...row,buy:Math.max(0,row.qty-Number(packagingStock[row.name]||0))})).filter(row=>row.buy>0)
  const stages=productionColumns(db)
  const action=overdue.length?{icon:'⏰',title:`Revisar ${overdue.length} pedido${overdue.length===1?'':'s'} vencido${overdue.length===1?'':'s'}`,detail:'Es la prioridad más urgente antes de seguir producción.',page:'orders',tone:'danger'}:
    stages.Pendiente.length?{icon:'✂',title:`Preparar corte de ${stages.Pendiente.length} pedido${stages.Pendiente.length===1?'':'s'}`,detail:'Hay pedidos activos que todavía no pasaron a corte.',page:'cut',tone:'primary'}:
    stages.Corte.length?{icon:'🧩',title:`Continuar ${stages.Corte.length} pedido${stages.Corte.length===1?'':'s'} en corte`,detail:'Revisar avance y pasar a pegado cuando corresponda.',page:'operations',tone:'primary'}:
    stages.Pegado.length?{icon:'🧴',title:`Pegar ${stages.Pegado.length} pedido${stages.Pegado.length===1?'':'s'}`,detail:'La siguiente etapa pendiente es pegado.',page:'operations',tone:'primary'}:
    stages.Embalaje.length?{icon:'📦',title:`Embalar ${stages.Embalaje.length} pedido${stages.Embalaje.length===1?'':'s'}`,detail:'Hay pedidos listos para preparar su salida.',page:'operations',tone:'primary'}:
    boxesToBuy.length?{icon:'🛒',title:`Comprar ${boxesToBuy.reduce((s,r)=>s+r.buy,0)} caja${boxesToBuy.reduce((s,r)=>s+r.buy,0)===1?'':'s'}`,detail:'Faltan cajas para cubrir los próximos 7 días.',page:'operations',tone:'warning'}:
    {icon:'✓',title:'Operación al día',detail:'No hay bloqueantes importantes detectados ahora.',page:'operations',tone:'ok'}
  const results=useMemo(()=>{const q=query.trim().toLocaleLowerCase('es');if(q.length<2)return[];return orders.filter(o=>[o.number,o.client,o.firstName,o.lastName,o.phone,o.dni,o.locality,...(o.items||[]).map(i=>i.figure)].filter(Boolean).join(' ').toLocaleLowerCase('es').includes(q)).slice(0,5)},[query,orders])
  return <><Title title="Hoy en Polifan" sub="Producción, pedidos y alertas importantes en una sola pantalla." actions={<><button className="ghost" onClick={()=>go('operations')}>⚡ Centro operativo</button><button className="primary" onClick={()=>go('new')}>＋ Nuevo pedido</button></>}/>
    <section className="v25-topbar"><div className="v25-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pedido, cliente, teléfono, DNI o figura…"/>{query&&<button onClick={()=>setQuery('')}>×</button>}</div>{results.length>0&&<div className="v25-results">{results.map(o=><button key={o.id} onClick={()=>go('orders')}><div><b>#{o.number} · {o.client||[o.firstName,o.lastName].filter(Boolean).join(' ')||'Sin nombre'}</b><small>{orderPieces(o)} piezas · {o.delivery||'sin fecha'}</small></div><Badge status={o.status}/></button>)}</div>}</section>
    <button className={'v25-now '+action.tone} onClick={()=>go(action.page)}><span>{action.icon}</span><div><small>QUÉ HACER AHORA</small><b>{action.title}</b><em>{action.detail}</em></div><i>›</i></button>
    {(overdue.length>0||todayPieces>=80||lowStock.length>0)&&<section className="v25-alerts">{overdue.length>0&&<button className="danger" onClick={()=>go('orders')}><span>⏰</span><div><b>{overdue.length} pedido{overdue.length===1?'':'s'} con fecha vencida</b><small>Revisar estado o fecha de entrega</small></div><i>›</i></button>}{todayPieces>=80&&<button className="warning" onClick={()=>go('calendar')}><span>⚠</span><div><b>Capacidad de hoy: {todayPieces}/{DAILY_PIECE_LIMIT}</b><small>{todayPieces>DAILY_PIECE_LIMIT?`Exceso de ${todayPieces-DAILY_PIECE_LIMIT}`:`Quedan ${free} lugares`}</small></div><i>›</i></button>}{lowStock.length>0&&<button className="info" onClick={()=>go('stock')}><span>◇</span><div><b>{lowStock.length} alertas de inventario</b><small>Hay piezas por debajo del mínimo</small></div><i>›</i></button>}</section>}
    <section className="v25-hero"><div><small>RESUMEN DE HOY</small><h2>{todayPieces>=DAILY_PIECE_LIMIT?'Producción completa':todayPieces>=70?'Día de alta carga':'Producción bajo control'}</h2><p>{todayPieces} piezas programadas · {todayOrders.length} entregas · {sheetsForPieces(todayPieces)} planchas aprox.</p><div className="v25-progress"><span style={{width:`${Math.min(100,Math.round(todayPieces/DAILY_PIECE_LIMIT*100))}%`}}/></div></div><strong>{todayPieces}<small> / {DAILY_PIECE_LIMIT}</small></strong></section>
    <section className="v25-focus"><button className="v25-focus-card primary" onClick={()=>go('cut')}><span>✂</span><div><small>PRODUCCIÓN</small><b>Preparar corte</b><em>{pendingPieces} piezas activas</em></div><i>›</i></button><button className="v25-focus-card" onClick={()=>go('sheetplanner')}><span>⚙</span><div><small>MOTOR</small><b>Generar placas</b><em>Smart-4</em></div><i>›</i></button><button className="v25-focus-card" onClick={()=>go('operations')}><span>📦</span><div><small>DESPACHOS</small><b>{todayOrders.length} para hoy</b><em>Preparar salidas</em></div><i>›</i></button><button className="v25-focus-card" onClick={()=>go('stock')}><span>◇</span><div><small>INVENTARIO</small><b>{lowStock.length?`${lowStock.length} alertas`:'Stock en orden'}</b><em>Ver existencias</em></div><i>›</i></button></section>
    <section className="v25-stats"><button onClick={()=>go('orders')}><small>Pedidos activos</small><b>{active.length}</b><span>{pendingPieces} piezas</span></button><button onClick={()=>go('monthly')}><small>Facturación mes</small><b>{money(revenue)}</b><span>{monthOrders.length} pedidos</span></button><button onClick={()=>go('calendar')}><small>Capacidad libre hoy</small><b>{free}</b><span>de {DAILY_PIECE_LIMIT} lugares</span></button><button onClick={()=>go('operations')}><small>Cajas a comprar</small><b>{boxesToBuy.reduce((s,r)=>s+r.buy,0)}</b><span>próximos 7 días</span></button></section>
    <div className="v25-bottom"><section className="panel v25-next"><div className="panel-heading"><div><small>AGENDA</small><h3>Próximas entregas</h3></div><button className="ghost" onClick={()=>go('orders')}>Ver todos</button></div>{next.map(o=><button key={o.id} onClick={()=>go('orders')}><div className="v25-date"><b>{String(o.delivery).slice(8,10)}</b><small>{new Date(o.delivery+'T12:00:00').toLocaleDateString('es-AR',{month:'short'}).replace('.','')}</small></div><div><b>#{o.number} · {o.client}</b><small>{orderPieces(o)} piezas · {o.deliveryType||o.carrier||'Logística'}</small></div><Badge status={o.status}/></button>)}{!next.length&&<p className="muted">No hay próximas entregas cargadas.</p>}</section>
      <section className="panel v25-boxes"><div className="panel-heading"><div><small>EMBALAJE</small><h3>Cajas · próximos 7 días</h3></div><button className="ghost" onClick={()=>go('operations')}>Gestionar stock</button></div>{boxes.map(row=>{const stock=Number(packagingStock[row.name]||0),buy=Math.max(0,row.qty-stock);return <div className="v25-boxrow" key={row.name}><div><b>{row.name}</b><small>Necesitás {row.qty} · stock {stock}</small></div><strong className={buy?'red-text':'green-text'}>{buy?`Comprar ${buy}`:'OK'}</strong></div>})}{!boxes.length&&<p className="muted">No hay cajas previstas para esta semana.</p>}</section></div>
  </>
}
