import React from 'react'
import {Title,Badge} from '../components/UI'
import {money} from '../lib/format'
import {stockRows,isOrderCommitted} from '../lib/inventory'
import {DAILY_PIECE_LIMIT,orderPieces,productionStatus,sheetsForPieces,todayArgentinaISO,argentinaNow} from '../lib/production'
import {estimatedOrderProfit} from '../lib/finance'
import {dispatchGroups,workload} from '../lib/operations'
const pct=(v,t)=>Math.max(0,Math.min(100,t?Math.round(v/t*100):0))
const dateLabel=date=>new Date(date+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'2-digit',month:'short'})
function StatCard({icon,label,value,detail,tone='purple',onClick}){return <button type="button" className={'dash-stat '+tone} onClick={onClick}><span className="dash-stat-icon">{icon}</span><span className="dash-stat-copy"><small>{label}</small><strong>{value}</strong>{detail&&<em>{detail}</em>}</span></button>}
export default function Dashboard({db,go}){
 const today=todayArgentinaISO(),activeOrders=(db.orders||[]).filter(o=>isOrderCommitted(o,today)),todayOrders=(db.orders||[]).filter(o=>o.delivery===today&&o.status!=='Cancelado'),pendingPieces=activeOrders.reduce((s,o)=>s+orderPieces(o),0)
 const [yearText,monthText]=argentinaNow().date.split('-'),month=Number(monthText),year=Number(yearText),monthly=(db.orders||[]).filter(o=>{const raw=(o.date||o.createdAt||'').slice(0,10);if(!raw)return false;const d=new Date(raw+'T12:00:00');return d.getMonth()+1===month&&d.getFullYear()===year&&o.status!=='Cancelado'})
 const revenue=monthly.reduce((s,o)=>s+Number(o.total||0),0),productionProfit=monthly.reduce((s,o)=>s+estimatedOrderProfit(o,db.costSettings).total,0),monthlyExpenses=(db.expenses||[]).filter(e=>{const raw=(e.date||'').slice(0,10);if(!raw)return false;const d=new Date(raw+'T12:00:00');return d.getMonth()+1===month&&d.getFullYear()===year}).reduce((s,e)=>s+Number(e.amount||0),0),netProfit=productionProfit-monthlyExpenses
 const lowRows=stockRows(db).filter(s=>s.total<=s.min),todayPieces=todayOrders.reduce((s,o)=>s+orderPieces(o),0),webPending=Number(db.webRequests?.filter?.(r=>r.status==='Pendiente de pago').length||0),todayProgress=pct(todayPieces,DAILY_PIECE_LIMIT),todayFree=Math.max(0,DAILY_PIECE_LIMIT-todayPieces),avgTicket=monthly.length?Math.round(revenue/monthly.length):0,load=workload(db),dispatch=dispatchGroups(db,today)
 const productionByDate=Object.entries((db.orders||[]).filter(o=>o.delivery&&o.status!=='Cancelado').reduce((a,o)=>{a[o.delivery]=(a[o.delivery]||0)+orderPieces(o);return a},{})).sort(([a],[b])=>a.localeCompare(b)).filter(([date])=>date>=today).slice(0,7)
 const nextDeliveries=(db.orders||[]).filter(o=>o.delivery&&o.delivery>=today&&o.status!=='Cancelado').sort((a,b)=>String(a.delivery).localeCompare(String(b.delivery))||String(a.number).localeCompare(String(b.number))).slice(0,6)
 return <><Title title="Centro de trabajo" sub="Lo urgente de hoy, producción, despachos, ventas y ganancia real." actions={<div className="dash-title-actions"><button className="ghost" onClick={()=>go('operations')}>⚡ Centro operativo</button><button className="primary" onClick={()=>go('new')}>＋ Nuevo pedido</button></div>}/>
 <section className="dash-hero"><div className="dash-hero-copy"><span className="dash-eyebrow">RESUMEN DE HOY</span><h2>{todayPieces>=DAILY_PIECE_LIMIT?'Producción completa para hoy':todayPieces>=70?'Día con alta carga de trabajo':'Producción bajo control'}</h2><p>{todayPieces} de {DAILY_PIECE_LIMIT} piezas programadas. Trabajo activo estimado: <b>{load.hours} horas</b>.</p><div className="dash-progress"><span style={{width:`${todayProgress}%`}}/></div><div className="dash-hero-meta"><b>{todayProgress}% ocupado</b><span>{sheetsForPieces(todayPieces)} planchas aprox.</span><span>{todayOrders.length} entregas</span></div></div><div className="dash-hero-number"><small>PIEZAS HOY</small><strong>{todayPieces}</strong><span>{todayFree} lugares libres</span></div></section>
 <div className="dash-stats-grid"><StatCard icon="📋" label="Pedidos activos" value={activeOrders.length} detail={`${pendingPieces} piezas pendientes`} onClick={()=>go('orders')}/><StatCard icon="🚚" label="Despachos hoy" value={todayOrders.length} detail={Object.entries(dispatch).map(([k,v])=>`${k}: ${v.length}`).join(' · ')||'Sin despachos'} tone="orange" onClick={()=>go('operations')}/><StatCard icon="💵" label="Facturación del mes" value={money(revenue)} detail={`${monthly.length} pedidos · ticket ${money(avgTicket)}`} tone="green" onClick={()=>go('monthly')}/><StatCard icon="✨" label="Ganancia neta estimada" value={money(netProfit)} detail={`Producción/embalaje descontados + gastos ${money(monthlyExpenses)}`} tone="blue" onClick={()=>go('costs')}/><StatCard icon="🛒" label="Solicitudes web" value={webPending} detail="Esperando confirmación" tone="pink" onClick={()=>go('webrequests')}/><StatCard icon="⚠" label="Stock bajo" value={lowRows.length} detail={lowRows.length?'Requiere atención':'Todo en orden'} tone={lowRows.length?'red':'teal'} onClick={()=>go('stock')}/></div>
 <div className="dash-main-grid"><section className="panel dash-production-panel"><div className="panel-heading"><div><span className="dash-eyebrow">PRÓXIMOS DÍAS</span><h3>Capacidad de producción</h3></div><button className="ghost" onClick={()=>go('calendar')}>Calendario completo</button></div><div className="dash-production-list">{productionByDate.map(([date,pieces])=>{const status=productionStatus(pieces),progress=pct(pieces,DAILY_PIECE_LIMIT);return <button type="button" className={'dash-production-row '+status} key={date} onClick={()=>go('calendar')}><div className="dash-date"><b>{dateLabel(date)}</b><small>{sheetsForPieces(pieces)} planchas aprox.</small></div><div className="dash-mini-progress"><span style={{width:`${progress}%`}}/></div><div className="dash-capacity"><strong>{pieces}/{DAILY_PIECE_LIMIT}</strong><small>{pieces>DAILY_PIECE_LIMIT?`Exceso ${pieces-DAILY_PIECE_LIMIT}`:pieces===DAILY_PIECE_LIMIT?'Completo':`${DAILY_PIECE_LIMIT-pieces} libres`}</small></div></button>})}{!productionByDate.length&&<div className="dash-empty"><b>No hay fechas futuras cargadas.</b></div>}</div></section><section className="panel dash-actions-panel"><span className="dash-eyebrow">ACCESOS RÁPIDOS</span><h3>¿Qué necesitás hacer?</h3><div className="dash-action-list"><button onClick={()=>go('operations')}><span>⚡</span><div><b>Operación de hoy</b><small>Despachos, pegado y cajas</small></div></button><button onClick={()=>go('new')}><span>＋</span><div><b>Crear pedido</b><small>Figuras + trabajos manuales</small></div></button><button onClick={()=>go('cut')}><span>✂</span><div><b>Lista para cortar</b><small>Piezas pendientes</small></div></button><button onClick={()=>go('costs')}><span>🧮</span><div><b>Actualizar costos</b><small>Placas, pegado y embalaje</small></div></button></div></section></div>
 <div className="dash-bottom-grid"><section className="panel"><div className="panel-heading"><div><span className="dash-eyebrow">AGENDA</span><h3>Próximas entregas</h3></div><button className="ghost" onClick={()=>go('orders')}>Ver pedidos</button></div><div className="dash-deliveries">{nextDeliveries.map(o=><div className="dash-delivery" key={o.id}><div className="dash-delivery-date"><strong>{new Date(o.delivery+'T12:00:00').toLocaleDateString('es-AR',{day:'2-digit'})}</strong><small>{new Date(o.delivery+'T12:00:00').toLocaleDateString('es-AR',{month:'short'}).replace('.','')}</small></div><div className="dash-delivery-main"><b>#{o.number} · {o.client}</b><small>{orderPieces(o)} piezas · {o.deliveryType||o.carrier||'Logística'}</small></div><Badge status={o.status}/></div>)}</div></section><section className="panel"><span className="dash-eyebrow">DESPACHOS HOY</span><h3>Por transporte</h3>{Object.entries(dispatch).map(([type,orders])=><button className="dash-alert info" key={type} onClick={()=>go('operations')}><span>📦</span><div><b>{type}</b><small>{orders.length} pedido{orders.length===1?'':'s'} · {orders.reduce((s,o)=>s+orderPieces(o),0)} piezas</small></div><i>›</i></button>)}{!Object.keys(dispatch).length&&<div className="dash-empty compact"><b>No hay despachos hoy.</b></div>}</section></div></>
}
