import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from '../supabase'
import {JOURNEY_EVENTS,trackingState} from '../lib/customerJourney'
const labels={confirmed:'Pedido agendado',production_cut:'En producción / corte',packing:'Para embalar',dispatched:'Despachado'}
const deliveryLabel=value=>{const raw=String(value||'').toLowerCase();if(raw.includes('retiro'))return 'Retiro en el local';if(raw.includes('via cargo')||raw.includes('vía cargo'))return 'Vía Cargo';return value||'Logística GBA/CABA'}
const dateLabel=value=>{if(!value)return 'A coordinar';const [y,m,d]=String(value).slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:value}
export default function PublicTracking({token}){
 const [state,setState]=useState({loading:true,row:null,error:''})
 useEffect(()=>{let alive=true;(async()=>{try{const {data,error}=await supabase.rpc('get_order_tracking',{p_token:token});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(alive)setState({loading:false,row:row||null,error:''})}catch(e){if(alive)setState({loading:false,row:null,error:e?.message||'No se pudo consultar el seguimiento.'})}})();return()=>{alive=false}},[token])
 const stages=useMemo(()=>trackingState({},state.row?.tracking_stage||JOURNEY_EVENTS.CONFIRMED),[state.row?.tracking_stage])
 if(state.loading)return <div className="center-screen">Consultando tu pedido…</div>
 return <main style={{minHeight:'100vh',background:'#f6f8fc',padding:'24px 14px',fontFamily:'Arial,sans-serif',color:'#172033'}}><section style={{maxWidth:720,margin:'0 auto',background:'#fff',borderRadius:22,padding:24,boxShadow:'0 12px 35px rgba(20,40,80,.10)'}}>
 <div style={{display:'flex',alignItems:'center',gap:14,borderBottom:'3px solid #1d5fbf',paddingBottom:16}}><img src="/logo-tu-vida-en-tinta.png" alt="Tu Vida en Tinta" style={{width:72,height:72,objectFit:'contain'}}/><div><small style={{fontWeight:800}}>TU VIDA EN TINTA · POLIFAN</small><h1 style={{margin:'4px 0',fontSize:28,color:'#1d5fbf'}}>Seguimiento de pedido</h1></div></div>
 {(!state.row||state.error)?<div style={{padding:'28px 4px'}}><h2>No encontramos este seguimiento</h2><p>Revisá que el enlace esté completo. Si el problema continúa, escribinos indicando tu número de pedido.</p></div>:<><div style={{padding:'22px 0 10px'}}><h2 style={{margin:'0 0 6px'}}>Pedido #{state.row.order_number}</h2><p style={{margin:0}}>Hola {String(state.row.customer_name||'').trim().split(/\s+/)[0]||'cliente'}. Este es el estado actualizado de tu pedido.</p></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,margin:'14px 0 24px'}}><div style={{background:'#f5f8fc',padding:14,borderRadius:14}}><small>Entrega prevista</small><b style={{display:'block',marginTop:4}}>{dateLabel(state.row.delivery_date)}</b></div><div style={{background:'#f5f8fc',padding:14,borderRadius:14}}><small>Modalidad</small><b style={{display:'block',marginTop:4}}>{deliveryLabel(state.row.delivery_type)}</b></div><div style={{background:'#f5f8fc',padding:14,borderRadius:14}}><small>Piezas</small><b style={{display:'block',marginTop:4}}>{state.row.pieces||0}</b></div></div>
 <h3>Estado: {labels[state.row.tracking_stage]||'Pedido agendado'}</h3><div style={{display:'grid',gap:10}}>{stages.map(s=><div key={s.key} style={{display:'flex',gap:12,alignItems:'center',padding:'13px 15px',borderRadius:14,border:s.state==='active'?'2px solid #1d5fbf':'1px solid #d8dfeb',opacity:s.state==='pending'?.55:1,background:s.state==='done'?'#f5f8fc':'#fff'}}><span style={{fontSize:20}}>{s.state==='done'?'✓':s.state==='active'?'●':'○'}</span><b>{s.label}</b></div>)}</div>
 <p style={{marginTop:22,fontSize:13,color:'#64748b'}}>La información se actualiza a medida que el pedido avanza por producción, embalaje y despacho.</p></>}</section></main>
}