import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from '../supabase'
import {Title} from '../components/UI'
import {money} from '../lib/format'
import {upsertClientFromOrder} from '../lib/clients'
import {estimateProductionAvailability,todayArgentinaISO} from '../lib/production'
import {downloadOrderReceiptJpg} from '../lib/orderReceipt'
import {downloadQuoteJpg} from '../lib/quoteReceipt'
import {catalogProducts,normalizeCatalogProducts} from '../lib/catalog'
import {stockRows} from '../lib/inventory'

const isPending=row=>['Pendiente de pago','Presupuesto enviado'].includes(row.status)
const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
function regularPrice(qty){if(qty<=0)return 0;if(qty<=5)return qty*6000;if(qty<=11)return 25000+(qty-6)*(25000/6);return 40000+(qty-12)*(40000/12)}
function lightPrice(qty){if(qty<=0)return 0;if(qty<=11)return qty*7000;if(qty<=23)return qty*6000;return qty*5000}
function customPrice(p,qty){const q=Math.max(0,Number(qty)||0);if(!q)return 0;if(p.price100&&q>=100)return q*(Number(p.price100)/100);if(p.price12&&q>=12)return q*(Number(p.price12)/12);if(p.price6&&q>=6)return q*(Number(p.price6)/6);if(p.priceUnit)return q*Number(p.priceUnit);if(p.fixedPrice)return q*Number(p.fixedPrice);return null}

export default function WebRequests({db,onSave}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[view,setView]=useState('pending'),[detail,setDetail]=useState(null),[editing,setEditing]=useState(false),[draftItems,setDraftItems]=useState([]),[draftCustomer,setDraftCustomer]=useState({})
 const products=useMemo(()=>normalizeCatalogProducts(db.customerCatalog?.length?db.customerCatalog:catalogProducts),[db.customerCatalog]);const inventory=useMemo(()=>stockRows(db),[db])
 async function load(){setLoading(true);const {data,error}=await supabase.from('web_requests').select('*').order('created_at',{ascending:false});if(error)alert('No se pudieron cargar las solicitudes: '+error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 function openDetail(row){setDetail(row);setDraftItems((row.items||[]).map(item=>({...item,qty:Number(item.qty||0)})));setDraftCustomer({...row.customer});setEditing(false)}
 function productFor(item){return products.find(p=>p.id===item.productId)||products.find(p=>norm(p.name)===norm(item.name))||null}
 function stockFor(item){const name=productFor(item)?.name||item.name;return inventory.find(r=>norm(r.figure)===norm(name))||{cut:0,ordered:0,inCut:0,free:0,projected:0}}
 function svgFor(item){const product=productFor(item);const components=(db.svgLibrary||[]).filter(x=>(product?.id&&x.productId===product.id)||norm(x.productName||x.modelName)===norm(product?.name||item.name));const roles=new Set(components.map(x=>x.role||'simple'));const simple=roles.has('simple');return {components,roles,complete:simple||(roles.has('tapa')&&roles.has('base')),simple}}
 function totalFor(items){let regular=0,lights=0,special=0;items.forEach(item=>{const p=productFor(item)||{},q=Number(item.qty||0),custom=customPrice(p,q);if(custom!==null)special+=custom;else if(p.category==='Figuras con luces'||p.category==='Palabras con luces')lights+=q;else regular+=q});return regularPrice(regular)+lightPrice(lights)+special}
 function nextQuoteCode(){const max=Math.max(0,...(db.quotes||[]).map(q=>Number(String(q.code||'').match(/\d+$/)?.[0]||0)));return `PRES-${String(max+1).padStart(4,'0')}`}
 function existingQuote(row){return (db.quotes||[]).find(q=>q.source==='Web'&&q.sourceId===row.id&&!['Cancelado'].includes(q.status))||null}
 async function createQuote(row){const c=detail?.id===row.id?draftCustomer:(row.customer||{}),items=((detail?.id===row.id?draftItems:row.items)||[]).filter(i=>Number(i.qty)>0).map(i=>({figure:i.name||i.figure,name:i.name||i.figure,productId:i.productId||'',measure:i.measure||'',qty:Number(i.qty)}));if(!items.length)return alert('La solicitud no tiene productos para presupuestar.');const current=existingQuote(row),quote={id:current?.id||crypto.randomUUID(),code:current?.code||nextQuoteCode(),source:'Web',sourceId:row.id,status:'Pendiente',date:todayArgentinaISO(),customer:c,client:c.name||[c.firstName,c.lastName].filter(Boolean).join(' '),firstName:c.firstName||'',lastName:c.lastName||'',phone:c.phone||'',dni:c.dni||'',email:c.email||'',address:c.address||'',betweenStreets:c.betweenStreets||'',locality:c.locality||'',district:c.district||'',province:c.province||'',postalCode:c.postalCode||'',deliveryType:c.method||'Logística',agencyDelivery:c.agencyDelivery||'',delivery:row.estimated_from||'',items,total:totalFor(items),notes:row.notes||'',createdAt:current?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const quotes=current?(db.quotes||[]).map(q=>q.id===current.id?quote:q):[...(db.quotes||[]),quote];const saved=await onSave({...db,quotes});if(saved?.ok===false)return;try{await downloadQuoteJpg(quote)}catch(err){console.error(err)};const {error}=await supabase.from('web_requests').update({status:'Presupuesto enviado'}).eq('id',row.id);if(error)console.error(error);setRows(rs=>rs.map(x=>x.id===row.id?{...x,status:'Presupuesto enviado'}:x));setDetail(d=>d?.id===row.id?{...d,status:'Presupuesto enviado'}:d);alert(`${quote.code} guardado y descargado en JPG.`)}
 async function saveDraft(){if(!detail)return;const items=draftItems.filter(i=>Number(i.qty)>0).map(i=>({...i,qty:Number(i.qty)}));if(!items.length)return alert('La solicitud debe conservar al menos un producto.');const customer={...draftCustomer,name:[draftCustomer.firstName,draftCustomer.lastName].filter(Boolean).join(' ').trim()||draftCustomer.name||''},quantity=items.reduce((s,i)=>s+Number(i.qty||0),0),estimated_total=totalFor(items);const {error}=await supabase.from('web_requests').update({items,quantity,estimated_total,customer}).eq('id',detail.id);if(error)return alert('No se pudo editar la solicitud: '+error.message);const updated={...detail,items,quantity,estimated_total,customer};setRows(rs=>rs.map(r=>r.id===detail.id?updated:r));setDetail(updated);setDraftItems(items);setDraftCustomer(customer);setEditing(false);alert('Solicitud web actualizada. Ya podés confirmarla.')}
 async function confirmRow(r){
  if(!window.confirm(`¿Confirmar el pago de ${r.code} y crear el pedido?`))return
  const {data:fresh,error:freshError}=await supabase.from('app_state').select('data').eq('id','main').maybeSingle();if(freshError)return alert('No se pudo verificar el número de pedido: '+freshError.message)
  const freshOrders=Array.isArray(fresh?.data?.orders)?fresh.data.orders:[]
  const already=freshOrders.find(o=>String(o.notes||'').includes(`Solicitud ${r.code}`));if(already){await supabase.from('web_requests').update({status:'Pago confirmado'}).eq('id',r.id);setRows(rs=>rs.map(x=>x.id===r.id?{...x,status:'Pago confirmado'}:x));setDetail(null);return alert(`Esta solicitud ya corresponde al pedido #${already.number}. No se creó un duplicado.`)}
  const next=String(Math.max(0,...freshOrders.map(x=>Number(x.number)||0))+1).padStart(3,'0'),c=r.customer||{},isPickup=(c.method||'Logística')==='Retiro en el local';let shippingCost=0,shippingPaid='No corresponde';if(!isPickup){const shippingInput=window.prompt('Costo de envío ya presupuestado (solo números):','0');if(shippingInput===null)return;shippingCost=Math.max(0,Number(String(shippingInput).replace(/[^0-9.,]/g,'').replace(',','.'))||0);shippingPaid=window.confirm('¿El costo de envío ya está PAGADO?\nAceptar = Pagado · Cancelar = Pendiente de pago')?'Pagado':'Pendiente de pago'}
  const recalculatedEstimate=!r.estimated_from?estimateProductionAvailability(freshOrders,Number(r.quantity||0),db.productionClosedDates||[]):null,resolvedDelivery=r.estimated_from||recalculatedEstimate?.productionDate||''
  const order={id:crypto.randomUUID(),number:next,date:todayArgentinaISO(),delivery:resolvedDelivery,firstName:c.firstName||String(c.name||'').trim().split(/\s+/)[0]||'',lastName:c.lastName||String(c.name||'').trim().split(/\s+/).slice(1).join(' '),client:c.name||[c.firstName,c.lastName].filter(Boolean).join(' '),phone:c.phone||'',dni:c.dni||'',email:c.email||'',address:c.address||'',betweenStreets:c.betweenStreets||'',locality:c.locality||'',district:c.district||'',province:c.province||'',postalCode:c.postalCode||'',zone:[c.locality,c.province].filter(Boolean).join(' · '),deliveryType:c.method||'Logística',carrier:c.method||'Logística',agencyDelivery:c.agencyDelivery||'',priority:'Normal',status:'Ingresado',paid:'Sí',shippingPackaging:c.method==='Retiro en el local'?'No':'Sí',shippingCost,shippingPaid,items:(r.items||[]).map(i=>({figure:i.name,productId:i.productId||'',qty:Number(i.qty||0)})),total:Number(r.estimated_total||0),notes:[r.notes,`Solicitud ${r.code}`].filter(Boolean).join(' · '),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}
  const clients=upsertClientFromOrder(db.clients||[],order),saved=await onSave({...db,orders:[...freshOrders,order],clients});if(saved?.ok===false)return alert('El pedido NO se guardó. La solicitud sigue pendiente; recargá y volvé a confirmar.')
  try{await downloadOrderReceiptJpg(order)}catch(err){console.error(err)}
  const {error}=await supabase.from('web_requests').update({status:'Pago confirmado'}).eq('id',r.id);if(error)return alert(`Pedido #${next} creado, pero no se pudo actualizar la solicitud: ${error.message}`)
  setRows(rs=>rs.map(x=>x.id===r.id?{...x,status:'Pago confirmado'}:x));setDetail(null);alert(`Pedido #${next} creado y verificado.`)
 }
 async function removeRow(r){if(!window.confirm(`¿Eliminar la solicitud ${r.code}?`))return;const {error}=await supabase.from('web_requests').update({status:'Eliminada'}).eq('id',r.id);if(error)return alert('No se pudo eliminar la solicitud: '+error.message);setRows(rs=>rs.map(x=>x.id===r.id?{...x,status:'Eliminada'}:x));setDetail(null)}
 function contact(row){const c=row.customer||{},phone=String(c.phone||'').replace(/\D/g,'');if(!phone)return alert('La solicitud no tiene un WhatsApp válido.');window.open(`https://wa.me/54${phone.replace(/^54/,'')}?text=${encodeURIComponent(`Hola ${c.firstName||c.name||''}, estamos revisando tu solicitud ${row.code}.`)}`,'_blank','noopener,noreferrer')}
 function printRequest(row){window.print()}
 const visible=useMemo(()=>view==='pending'?rows.filter(isPending):rows.filter(row=>!isPending(row)),[rows,view]),pendingCount=rows.filter(isPending).length
 return <><Title title="Solicitudes web" sub="Revisá y editá datos, entrega y productos antes de confirmar el pago y crear el pedido."/><div className="request-tabs"><button className={view==='pending'?'active':''} onClick={()=>setView('pending')}>Pendientes ({pendingCount})</button><button className={view==='history'?'active':''} onClick={()=>setView('history')}>Historial</button></div><div className="panel table-wrap"><table><thead><tr><th>Código</th><th>Cliente</th><th>Piezas</th><th>Entrega estimada</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><b>{r.code}</b></td><td>{r.customer?.name}</td><td>{r.quantity}</td><td>{r.estimated_from||'Fecha a confirmar'}</td><td>{money(r.estimated_total)}</td><td>{r.status}</td><td><button className="ghost" onClick={()=>openDetail(r)}>👁️ Ver / editar</button>{isPending(r)&&<button className="primary" onClick={()=>confirmRow(r)}>Confirmar directo</button>}</td></tr>)}</tbody></table>{loading&&<p>Cargando…</p>}</div>{detail&&<RequestDetail row={detail} items={draftItems} setItems={setDraftItems} customer={draftCustomer} setCustomer={setDraftCustomer} editing={editing} setEditing={setEditing} onClose={()=>setDetail(null)} onSave={saveDraft} onConfirm={()=>confirmRow(detail)} onRemove={()=>removeRow(detail)} onContact={()=>contact(detail)} onPrint={()=>printRequest(detail)} onQuote={()=>createQuote(detail)}/>}</>
}
function RequestDetail({row,items,setItems,customer,setCustomer,editing,setEditing,onClose,onSave,onConfirm,onRemove,onContact,onPrint,onQuote}){return <div className="modal-backdrop"><div className="modal"><h3>{row.code}</h3><p><b>{customer.name}</b> · {row.quantity} piezas · {money(row.estimated_total)}</p><div className="actions"><button onClick={onClose}>Cerrar</button><button onClick={()=>setEditing(!editing)}>Editar</button><button onClick={onQuote}>Presupuesto</button><button onClick={onContact}>WhatsApp</button><button onClick={onPrint}>Imprimir</button><button className="primary" onClick={onConfirm}>Confirmar directo</button><button onClick={onRemove}>Eliminar</button></div>{editing&&<><p>Edición básica de cantidades:</p>{items.map((i,n)=><label key={n} className="block">{i.name}<input type="number" value={i.qty} onChange={e=>setItems(a=>a.map((x,k)=>k===n?{...x,qty:e.target.value}:x))}/></label>)}<button className="primary" onClick={onSave}>Guardar cambios</button></>}</div></div>}
