import './finalize-v25.0.76.mjs'
import fs from 'node:fs'
const motorFile='src/pages/MotorDefinitivo.jsx';let motor=fs.readFileSync(motorFile,'utf8')
if(motor.includes('widthCm:122.4'))motor=motor.replace('widthCm:122.4','widthCm:121.8');else if(!motor.includes('widthCm:121.8'))throw new Error('v25.0.77: área útil desconocida')
if(motor.includes('const x=3+Number(p.xCm||0)*10,y=6+Number(p.yCm||0)*10,angle=Number(p.angle||0)'))motor=motor.replace('const x=3+Number(p.xCm||0)*10,y=6+Number(p.yCm||0)*10,angle=Number(p.angle||0)','const x=6+Number(p.xCm||0)*10,y=6+Number(p.yCm||0)*10,angle=Number(p.angle||0)');else if(!motor.includes('const x=6+Number(p.xCm||0)*10,y=6+Number(p.yCm||0)*10'))throw new Error('v25.0.77: offset desconocido')
motor=motor.replaceAll('1224 × 568 mm útiles · margen vertical reforzado 6 mm','1218 × 568 mm útiles · guarda real 6 mm en los cuatro lados');fs.writeFileSync(motorFile,motor)
const appFile='src/AppV2.jsx';let app=fs.readFileSync(appFile,'utf8');const oldMissing="const missing=full?keys:keys.filter(k=>!loadedRef.current.has(k))";const newMissing="const liveOrderPages=new Set(['orders','new','sheetplanner']);const missing=full?keys:keys.filter(k=>(k==='orders'&&liveOrderPages.has(target))||!loadedRef.current.has(k))";if(app.includes(oldMissing))app=app.replace(oldMissing,newMissing);else if(!app.includes("liveOrderPages=new Set(['orders','new','sheetplanner'])"))throw new Error('v25.0.77: política cache desconocida');fs.writeFileSync(appFile,app)
const orderFormFile='src/pages/OrderForm.jsx';let orderForm=fs.readFileSync(orderFormFile,'utf8');const clientsAnchor='const clients=upsertClientFromOrder(db.clients||[],final)',receiptAnchor="if(!editing){try{await downloadOrderReceiptJpg(final)}catch(err){console.error(err)}}";const clientsPos=orderForm.indexOf(clientsAnchor),receiptPos=orderForm.indexOf(receiptAnchor,clientsPos);if(clientsPos>=0&&receiptPos>=0){const saveStart=orderForm.indexOf('const saved=await onSave(',clientsPos),saveEndBase=orderForm.indexOf('if(saved?.ok===false)return',saveStart);if(saveStart>=0&&saveEndBase>=0&&saveEndBase<receiptPos){const saveEnd=saveEndBase+'if(saved?.ok===false)return'.length;orderForm=orderForm.slice(0,saveStart)+"const saved=await onSave(editing?{...db,orders,_onlyKeys:['orders']}:{...db,orders,clients,_onlyKeys:['orders','clients']});if(saved?.ok===false)return"+orderForm.slice(saveEnd)}};if(!orderForm.includes("editing?{...db,orders,_onlyKeys:['orders']}"))throw new Error('v25.0.78: guardado pedido incompleto');fs.writeFileSync(orderFormFile,orderForm)
const dataFile='src/lib/v2Data.js';let data=fs.readFileSync(dataFile,'utf8');const oldWeb="  webrequests:['quotes','orders'],",newWeb="  webrequests:['quotes','orders','customerCatalog','svgLibrary'],";if(data.includes(oldWeb))data=data.replace(oldWeb,newWeb);else if(!data.includes(newWeb))throw new Error('v25.0.79: secciones web desconocidas');fs.writeFileSync(dataFile,data)
const cssFile='src/v2-mobile-hotfix.css';let css=fs.readFileSync(cssFile,'utf8');const marker='/* v25.0.79 · legibilidad global PC + móvil */';if(!css.includes(marker)){css+=`\n${marker}\n.v2-shell .content>main{font-size:16px!important;line-height:1.45!important}\n.v2-shell table{font-size:15px!important}\n`;fs.writeFileSync(cssFile,css)}
console.log('v25.0.79 FINALIZE OK · idempotente')
