import './finalize-v25.0.67.mjs'
import fs from 'node:fs'
function one(text,before,after,label){const count=text.split(before).length-1;if(count===0){if(text.includes(after))return text;console.log(`finalize-v25.0.68: ${label} ya no usa bloque histórico; se conserva`);return text}if(count!==1)throw new Error(`finalize-v25.0.68: ${label} aparece ${count} veces`);return text.replace(before,after)}
const motorFile='src/pages/MotorDefinitivo.jsx';let motor=fs.readFileSync(motorFile,'utf8');const payloadRx=/const payload=\{[^\n;]*kits:industrial\.kits[^\n;]*\}/g;const payloadMatches=motor.match(payloadRx)||[];if(payloadMatches.length===1){let payload=payloadMatches[0];payload=payload.replace(/widthCm:[0-9.]+/,'widthCm:122.4').replace(/heightCm:[0-9.]+/,'heightCm:57.4');motor=motor.replace(payloadMatches[0],payload)}
motor=one(motor,"const x=Number(p.xCm||0)*10,y=Number(p.yCm||0)*10,angle=Number(p.angle||0)","const x=3+Number(p.xCm||0)*10,y=3+Number(p.yCm||0)*10,angle=Number(p.angle||0)",'offset de borde de 3 mm')
if(!motor.includes('attemptsCount:Array.isArray(data.attempts)'))motor=one(motor,"targetDensityReached:Boolean(data.targetDensityReached)","engineName:String(data.engine||data.source||'Sparrow'),selectionStrategy:String(data.selectionStrategy||''),runtimeSolver:String(data.runtimeSolver?.qualname||data.runtimeSolver?.name||data.runtimeSolver?.module||''),attemptsCount:Array.isArray(data.attempts)?data.attempts.length:0,requiredGapMm:3,motorGapMm:3,targetDensityReached:Boolean(data.targetDensityReached)",'telemetría del motor')
fs.writeFileSync(motorFile,motor)
const orderFile='src/pages/OrderForm.jsx';let order=fs.readFileSync(orderFile,'utf8');if(!order.includes('promoManualQty'))console.log('finalize-v25.0.68: promo manual ya evolucionó; se conserva implementación actual');fs.writeFileSync(orderFile,order)
console.log('v25.0.68 FINALIZE OK · validación compatible')
