import './finalize-v25.0.77.mjs'
import fs from 'node:fs'
const appFile='src/AppV2.jsx';let app=fs.readFileSync(appFile,'utf8')
const refsOld="const loadedRef=useRef(new Set(cached.keys||[])),baselineRef=useRef(initial),requestRef=useRef(0)";const refsNew="const loadedRef=useRef(new Set(cached.keys||[])),baselineRef=useRef(initial),requestRef=useRef(0),navigationRef=useRef(0)"
if(app.includes(refsOld))app=app.replace(refsOld,refsNew);else if(!app.includes('navigationRef=useRef(0)'))throw new Error('v25.0.81: refs de navegación incompletos')
const goNew="async function go(id){const navigation=++navigationRef.current;if(id==='new'){try{localStorage.removeItem('polifan-order-draft-v1')}catch{}setEditingOrder(null)}setMobileOpen(false);await ensurePage(id,false);if(navigation!==navigationRef.current)return;setPage(id)}";const goRx=/function go\(id\)\{[\s\S]*?\}\n  function openQuoteAsOrder/
if(goRx.test(app))app=app.replace(goRx,goNew+'\n  function openQuoteAsOrder');app=app.replace('async async function go','async function go')
const asideOld="<aside className={'sidebar '+(mobileOpen?'open':'')}>";const asideNew="<aside className={'sidebar '+(mobileOpen?'open':'')} onWheel={e=>{const el=e.currentTarget;if(el.scrollHeight>el.clientHeight){e.preventDefault();el.scrollTop+=e.deltaY}}}>";if(app.includes(asideOld))app=app.replace(asideOld,asideNew)
if(app.includes('<Suspense fallback={<Loading/>}>'))app=app.replace('<Suspense fallback={<Loading/>}>','<Suspense fallback={<div className="v2-module-loader"><b>Cargando módulo…</b><span>Un momento</span></div>}>')
fs.writeFileSync(appFile,app)
const motorFile='src/pages/MotorDefinitivo.jsx';let motor=fs.readFileSync(motorFile,'utf8');const importOld="import React,{useEffect,useMemo,useState} from 'react'";if(motor.includes(importOld))motor=motor.replace(importOld,"import React,{useEffect,useMemo,useRef,useState} from 'react'")
const storageAnchor="function loadSavedPlans(){\n  try{return JSON.parse(localStorage.getItem(LAB_STORAGE)||'[]')||[]}\n  catch{return []}\n}";if(!motor.includes('function loadRuntimePlans()')&&motor.includes(storageAnchor))motor=motor.replace(storageAnchor,storageAnchor+"\nlet runtimePlans=null\nfunction loadRuntimePlans(){return runtimePlans||loadSavedPlans()}");motor=motor.replace('const [plans,setPlans]=useState(loadSavedPlans)','const [plans,setPlans]=useState(loadRuntimePlans)')
const modeOld="  const [choosingMode,setChoosingMode]=useState(false)\n\n  useEffect(()=>{if(plans.length)savePlans(plans)},[plans])\n  useEffect(()=>{\n    const active=loadActiveJob()\n    if(active?.jobId){resumeActiveJob(active)}\n  },[])";const modeNew="  const [choosingMode,setChoosingMode]=useState(false)\n  const resumeRef=useRef('')\n\n  useEffect(()=>{runtimePlans=plans;if(plans.length)savePlans(plans)},[plans])\n  useEffect(()=>{\n    const active=loadActiveJob()\n    if(!active?.jobId||resumeRef.current===active.jobId)return\n    if(!(db.svgLibrary||[]).length||!(db.orders||[]).length)return\n    resumeRef.current=active.jobId\n    resumeActiveJob(active)\n  },[db.svgLibrary,db.orders])";if(motor.includes(modeOld))motor=motor.replace(modeOld,modeNew)
fs.writeFileSync(motorFile,motor)
const cssFile='src/v2-mobile-hotfix.css';let css=fs.readFileSync(cssFile,'utf8');const marker='/* v25.0.81 · navegación fluida + rueda sidebar */';if(!css.includes(marker)){css+=`\n${marker}\n.v2-shell .sidebar{overscroll-behavior:contain!important;scrollbar-gutter:stable!important}\n.v2-shell .v2-module-loader{min-height:180px;display:grid;place-items:center;align-content:center;gap:5px;color:#39445a}\n`;fs.writeFileSync(cssFile,css)}
const versionFile='src/version.js';let version=fs.readFileSync(versionFile,'utf8');version=version.replace(/APP_VERSION='[^']*'/,"APP_VERSION='25.0.81'").replace(/APP_VERSION_LABEL='[^']*'/,"APP_VERSION_LABEL='v25.0.81'");fs.writeFileSync(versionFile,version)
if(!app.includes('navigationRef=useRef(0)')||!motor.includes("const resumeRef=useRef('')")||!motor.includes('useState(loadRuntimePlans)'))throw new Error('v25.0.81: validación final incompleta')
console.log('v25.0.81 FINALIZE OK · idempotente')
